# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db885849356bf594f752b4065141ba38c7b360fab22f97f6fbfeab5937d19579c048cad8a3c1ddc1a7349f3c4cb1ec791864b409f9e579889d33ff55f6f1fb20

test:
  secret_key_base: 6ce05002a348ebf1030524ed66609be61590a2c615896f2772449e6ac9178161d7b6c2fea0420923d4b5b580be60b2bba6c1f4f7ffccb4ef54271b8e774768ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
